### INDEX
GET http://localhost:3000/offers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDU0Njg2MjJ9.Ma1b-dwKCeEY0ypXt8JRgndQh_utfeuUNJKXfcl8gjA



###CREATE
POST http://localhost:3000/offers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDU0NjYwMzR9.irPNRv9G331K80_t4s9n9KG-52hfRpsR9E0ZXTizvoU
Content-Type: application/json

{
  "opportunity_id": 2,
  "candidate_id": 1
}

### DESTROY
DELETE http://localhost:3000/offers/10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDU0NjYwMzR9.irPNRv9G331K80_t4s9n9KG-52hfRpsR9E0ZXTizvoU
