### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Paul Recruiter",
  "email": "paul@test.com",
  "password": "password",
  "candidate": false,
  "password_confirmation": "password"
}

###

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "kenny@email.com",
  "password": "password"
}