### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Eric Candidate",
  "email": "eric@test.com",
  "password": "password",
  "candidate": true,
  "password_confirmation": "password"
}

###

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "eric@test.com",
  "password": "password"
}