###CREATE
POST http://localhost:5000/candidates
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDU4MjI1MzR9.Kz-oreblO8Mp0jAU2iHTCu2sWyoLF1lZCW7Vd8uWJvI
Content-Type: application/json

{
  "user_id": 1
}

### DESTROY
DELETE http://localhost:5000/candidates
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDU0NjQyOTB9.4RHQ-TfFmmucPpz5elYw0ixxYFMD8NNNjnMLPVmOqEI

### GET

GET http://localhost:5000/candidates
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDU4MjI1MzR9.Kz-oreblO8Mp0jAU2iHTCu2sWyoLF1lZCW7Vd8uWJvI
Content-Type: application/json
### GET by id

GET http://localhost:5000/candidates/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDU4MjI1MzR9.Kz-oreblO8Mp0jAU2iHTCu2sWyoLF1lZCW7Vd8uWJvI
Content-Type: application/json