###CREATE
POST http://localhost:3000/candidates
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNjQ1Mzk4NzIyfQ.54LTJoH0y7Jvh8km2bArE8nuObxPTszmXyB3UjbInt4
Content-Type: application/json

{
  "user_id": 1
}

### DESTROY
DELETE http://localhost:3000/candidates
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDU0NjQyOTB9.4RHQ-TfFmmucPpz5elYw0ixxYFMD8NNNjnMLPVmOqEI

### GET

GET http://localhost:3000/candidates
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDU1MDUwMzB9.DJGbK3P9A9n1HtgwkXIREc7APFvuF1q5Us28DHhKoZ4
Content-Type: application/json