###CREATE
POST http://localhost:5000/offers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDU0Njk3NTR9.8lPaxJxjBd2fdxGaYP5K7seqjGzS6mWwQ0vJaIdR5uA
Content-Type: application/json

{
  "opportunity_id": 2,
  "candidate_id": 1
}

### DESTROY
DELETE http://localhost:5000/offers/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2N…4MzN9.LTbFv2IWVoXJSp18SRoYx69uC9FYcraGf5fElX00a30

### GET

GET http://localhost:5000/offers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDU4MTI4MzN9.LTbFv2IWVoXJSp18SRoYx69uC9FYcraGf5fElX00a30