###CREATE
POST http://localhost:3000/offers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDU0Njk3NTR9.8lPaxJxjBd2fdxGaYP5K7seqjGzS6mWwQ0vJaIdR5uA
Content-Type: application/json

{
  "opportunity_id": 2,
  "candidate_id": 1
}

### DESTROY
DELETE http://localhost:3000/offers/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDU0NjYwMzR9.irPNRv9G331K80_t4s9n9KG-52hfRpsR9E0ZXTizvoU

### GET

GET http://localhost:3000/offers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDU0Njk3NTR9.8lPaxJxjBd2fdxGaYP5K7seqjGzS6mWwQ0vJaIdR5uA