###CREATE
POST http://localhost:5000/opportunities
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDU0Njc3NjJ9.RyZ1TDpwtc2Iw7SYEBCUg0rQprn9KsWZOb6Y-ZRnMfc
Content-Type: application/json

{
  "job_title": "AI expert.",
  "job_description": "dude idk anything about AI."
}
