###CREATE
POST http://localhost:5000/recruiters
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNjQ1Mzk4NzIyfQ.54LTJoH0y7Jvh8km2bArE8nuObxPTszmXyB3UjbInt4
Content-Type: application/json

{
  "company_name": "Recruiting Company Inc."
}

### DESTROY
DELETE http://localhost:5000/recruiters/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDU0NjM2MzZ9.bX96jt_07atjLXHEbY0oij3uCTEwyh3qNHScsI-7xm8

###
GET http://localhost:5000/recruiters
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDU1NDMzMzh9.QPZmuP09RiN0hAeFmU8uhN4nkjsW5BCOLYr-XUllTbE
Content-Type: application/json

###
GET http://localhost:5000/recruiters/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDU1NDMzMzh9.QPZmuP09RiN0hAeFmU8uhN4nkjsW5BCOLYr-XUllTbE
Content-Type: application/json