### Users create (signup)
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Ian B",
  "email": "test@test.com",
  "password": "password",
  "candidate": false,
  "password_confirmation": "password"
}

###

POST http://localhost:5000/sessions
Content-Type: application/json

{
  "email": "ianb@tes.com",
  "password": "password"
}

###  for recruiter testing use jwt generated below
POST http://localhost:5000/sessions
Content-Type: application/json

{
  "email": "kenny@email.com",
  "password": "password"
}